version: '2'
services:
    mongodb-backup:
        image: 'tutum/mongodb-backup:latest'
        environment:
          - MONGODB_PORT=27017
          - INIT_BACKUP=yes
        volumes:
          - ./backup:/backup
